### ISSUE TITLE
Error: configmap "backend" not found

### ISSUE THREAD

**Issue by Startouf** [itzmanish/ecr-token-renew#5]
All jobs are stuck in pending because of this error

> Error: configmap "backend" not found

Your code contains this reference multiple times `configMapKeyRef: "backend"`

Seems like there is something missing. Either in the code or your readme.

**Comment by itzmanish** [comment]
Thanks for pointing it out, it was missing from the documentation that the default value of `configMapKeyRef` is set to `backend`. That was for my use case where I have backend config available so I put that as default. You can always override it with custom.yaml and you need to point the `configMapKeyRef` value to correct configmap where AWS keys are present.

**Comment by itzmanish** [comment]
Closing the issue as I have updated the readme for this.
