### ISSUE TITLE
DOCKER REGISTRIES

### ISSUE THREAD

**Issue by mdubs45** [itzmanish/ecr-token-renew#6]
I may be missing something, but I see where the golang script is using envVarRegistries, but do not see that environment variable being set in the job.yaml or jobs.yaml?

**Comment by itzmanish** [comment]
Hi @mdubs45! Thanks for pointing it out. I will update the `jobs.yaml` for the missing `envVarRegistries`.

**Comment by itzmanish** [comment]
I have fixed this issue and it's already released in v0.1.4. Please upgrade to the latest.
